export interface ReportSchema { id: string; reporterId: string; targetType: 'POST' | 'VIDEO' | 'COMMENT' | 'USER' | 'PRODUCT' | 'AD' | 'COMMUNITY' | 'MESSAGE'; targetId: string; category: string; description?: string; status: 'OPEN' | 'UNDER_REVIEW' | 'ACTION_REQUIRED' | 'RESOLVED' | 'REJECTED' | 'ESCALATED'; createdAt: unknown; updatedAt: unknown; }
export interface ModerationCaseSchema { id: string; targetType: string; targetId: string; sourceReportIds: string[]; classification: string; status: 'OPEN' | 'REVIEWING' | 'ACTIONED' | 'APPEALED' | 'CLOSED'; assignedTo?: string; createdAt: unknown; updatedAt: unknown; }
export interface ModerationActionSchema { id: string; caseId: string; moderatorId: string; action: 'NO_ACTION' | 'WARNING' | 'LIMIT' | 'HIDE' | 'REMOVE' | 'SUSPEND' | 'BAN' | 'BLOCK_PRODUCT' | 'BLOCK_AD'; reason: string; createdAt: unknown; }
export interface RewardWalletSchema { id: string; userId: string; availableCents: number; pendingCents: number; lifetimeEarnedCents: number; lifetimeWithdrawnCents: number; currency: string; updatedAt: unknown; }
export interface RewardTaskSchema { id: string; title: string; description: string; type: 'WATCH' | 'ENGAGE' | 'CAMPAIGN' | 'CUSTOM'; rewardCents: number; enabled: boolean; dailyLimit?: number; createdAt: unknown; updatedAt: unknown; }
export interface RewardTransactionSchema { id: string; userId: string; type: 'EARN' | 'ADJUSTMENT' | 'REVERSAL' | 'WITHDRAWAL'; amountCents: number; source: string; idempotencyKey: string; createdAt: unknown; }
export interface AdCampaignSchema { id: string; advertiserId: string; name: string; status: 'DRAFT' | 'PENDING_REVIEW' | 'ACTIVE' | 'PAUSED' | 'REJECTED' | 'ENDED'; budgetCents: number; approvedDomains: string[]; createdAt: unknown; updatedAt: unknown; }
export interface AdSchema { id: string; campaignId: string; advertiserId: string; format: 'POST' | 'VIDEO' | 'STORY' | 'BANNER'; creativeStoragePath?: string; destinationUrl?: string; destinationDomain?: string; status: 'DRAFT' | 'PENDING_REVIEW' | 'ACTIVE' | 'PAUSED' | 'REJECTED'; approvedDomainLocked: boolean; createdAt: unknown; updatedAt: unknown; }
export interface AffiliateCommissionSchema { id: string; affiliateId: string; orderId: string; shopId: string; amountCents: number; status: 'PENDING' | 'APPROVED' | 'REVERSED' | 'PAID'; idempotencyKey: string; createdAt: unknown; updatedAt: unknown; }
