import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { env } from './config/env.js';
import { connectDatabases } from './infrastructure/database.js';
import { errorHandler, rateLimit, requestContext } from './middleware/security.js';
import { requireAuth } from './middleware/firebase-auth.js';
import flowRoutes from './routes/flow.routes.js';

const app=express();
app.disable('x-powered-by');
app.use(requestContext);
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:env.CORS_ORIGIN,credentials:true}));
app.use(rateLimit());
app.use(express.json({limit:'10mb'}));
app.get('/health',(_req,res)=>res.json({status:'ok',service:'flow-api',database:'firebase'}));
app.get('/api/v1/me',requireAuth,(req,res)=>res.json({uid:req.actor!.uid,admin:req.actor!.admin,permissions:req.actor!.permissions}));
app.use('/api/v1',flowRoutes);
app.use(errorHandler);
await connectDatabases();
app.listen(env.PORT,()=>console.log(`FLOW API listening on :${env.PORT}`));
