import {useMemo,useState} from 'react';
import {ArrowLeft,BarChart3,BookOpen,BriefcaseBusiness,CalendarDays,CheckCircle2,ChevronRight,Coins,Eye,Heart,LayoutDashboard,Play,Plus,Rocket,Search,Settings,Share2,ShieldCheck,ShoppingBag,Sparkles,TrendingUp,Users,Video,Wallet, X} from 'lucide-react';
import './creator.css';

const videos=[
 {title:'Kawaizinho chegou com mais uma dica…',views:'26,4 mil',likes:'896',comments:'27',shares:'366',img:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=700&q=85',date:'02 set 2026',completion:'42%'},
 {title:'Como criar conteúdo que realmente conecta',views:'12,8 mil',likes:'542',comments:'31',shares:'118',img:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=700&q=85',date:'01 set 2026',completion:'58%'},
 {title:'Meu bastidor de hoje no FLOW',views:'8,7 mil',likes:'391',comments:'18',shares:'72',img:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=700&q=85',date:'30 ago 2026',completion:'51%'}
];
const actions=[['Tarefa do criador','Complete desafios e oportunidades',Coins],['Ganhos por views','Acompanhe sua monetização',Wallet],['Parcerias','Encontre oportunidades com marcas',BriefcaseBusiness],['Impulsionar','Amplie o alcance de uma publicação',Rocket],['Academia','Aprenda a criar melhor',BookOpen],['Verificação','Fortaleça a credibilidade do perfil',ShieldCheck]] as const;

const go=(p:string)=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'));scrollTo(0,0)};

export default function CreatorCenter(){
 const [tab,setTab]=useState<'overview'|'posts'|'followers'|'income'>('overview');
 const [period,setPeriod]=useState<'7'|'30'>('7');
 const [showCreate,setShowCreate]=useState(false);
 const [range,setRange]=useState<'views'|'likes'>('views');
 const totals=period==='7'?{views:'26,4 mil',delta:'+314',followers:'117',fdelta:'+4',income:'R$ 0,00'}:{views:'84,7 mil',delta:'+1.284',followers:'128',fdelta:'+11',income:'R$ 0,00'};
 const chart=useMemo(()=>period==='7'?[32,45,39,61,54,72,88]:[24,32,29,45,42,54,49,66,61,72,68,84],[period]);
 return <div className="creator-shell">
  <header className="creator-top"><button className="back" onClick={()=>go('/app')}><ArrowLeft/></button><div className="creator-brand"><img src="/flow-logo.svg" alt="FLOW"/><span>Creator</span></div><div className="creator-search"><Search/><input placeholder="Pesquisar no FLOW"/></div><button className="top-icon"><BellDot/></button><button className="avatar" onClick={()=>go('/app/perfil')}><img src="https://i.pravatar.cc/80?img=68"/></button></header>
  <main className="creator-main">
   <section className="creator-heading"><div><span className="eyebrow"><Sparkles/> FLOW CREATOR</span><h1>Central do Criador</h1><p>Entenda seu desempenho, cresça sua comunidade e descubra novas oportunidades.</p></div><button className="create-btn" onClick={()=>setShowCreate(true)}><Plus/> Criar publicação</button></section>
   <section className="creator-profile"><div className="creator-user"><img src="https://i.pravatar.cc/120?img=68"/><div><h2>Seu perfil FLOW <CheckCircle2/></h2><span>@flow.creator</span><p>11 direitos de criador · Perfil público</p></div></div><div className="level"><b>Prata</b><span>11 Direitos</span><div><i style={{width:'58%'}}/></div></div></section>
   <nav className="creator-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard/>Visão geral</button><button className={tab==='posts'?'active':''} onClick={()=>setTab('posts')}><Video/>Publicações</button><button className={tab==='followers'?'active':''} onClick={()=>setTab('followers')}><Users/>Seguidores</button><button className={tab==='income'?'active':''} onClick={()=>setTab('income')}><Wallet/>Renda</button></nav>
   {tab==='overview'&&<Overview totals={totals} period={period} setPeriod={setPeriod} chart={chart} range={range} setRange={setRange}/>} 
   {tab==='posts'&&<Posts/>}
   {tab==='followers'&&<Followers period={period}/>} 
   {tab==='income'&&<Income/>}
   <section className="creator-tools"><div className="section-title"><div><span className="eyebrow">FERRAMENTAS</span><h2>Faça seu FLOW crescer</h2></div><button>Ver todas <ChevronRight/></button></div><div className="tool-grid">{actions.map(([name,desc,Icon])=><button className="tool-card" key={name}><span className="tool-icon"><Icon/></span><span><b>{name}</b><small>{desc}</small></span><ChevronRight/></button>)}</div></section>
  </main>
  {showCreate&&<CreateModal close={()=>setShowCreate(false)}/>} 
 </div>
}

function BellDot(){return <span className="bell-dot"><span/></span>}
function Overview({totals,period,setPeriod,chart,range,setRange}:{totals:any;period:string;setPeriod:(v:any)=>void;chart:number[];range:string;setRange:(v:any)=>void}){
 return <>
  <section className="metrics"><Metric icon={Eye} label="Visualizações" value={totals.views} delta={totals.delta}/><Metric icon={Users} label="Seguidores" value={totals.followers} delta={totals.fdelta}/><Metric icon={Wallet} label="Renda" value={totals.income}/><Metric icon={Heart} label="Curtidas" value={period==='7'?'896':'2.418'} delta={period==='7'?'+14':'+87'}/></section>
  <div className="period-row"><div><button className={period==='7'?'active':''} onClick={()=>setPeriod('7')}>7 dias</button><button className={period==='30'?'active':''} onClick={()=>setPeriod('30')}>30 dias</button></div><span>Atualizado agora</span></div>
  <section className="analytics-grid"><article className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">DESEMPENHO</span><h3>Visão geral das publicações</h3></div><select value={range} onChange={e=>setRange(e.target.value as any)}><option value="views">Visualizações</option><option value="likes">Curtidas</option></select></div><div className="chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 600 220" preserveAspectRatio="none"><polyline points={chart.map((v,i)=>`${i*(600/(chart.length-1))},${210-v*2}`).join(' ')} fill="none" stroke="url(#flowGrad)" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/><defs><linearGradient id="flowGrad"><stop stopColor="#2663eb"/><stop offset=".5" stopColor="#00d2be"/><stop offset="1" stopColor="#f24882"/></linearGradient></defs></svg><div className="chart-labels"><span>7 dias atrás</span><span>Hoje</span></div></div></article><article className="panel insight"><div className="insight-icon"><TrendingUp/></div><span className="eyebrow">INSIGHT FLOW</span><h3>Seu conteúdo está ganhando alcance.</h3><p>Continue publicando com consistência. Seus resultados recentes mostram evolução de visualizações e seguidores.</p><button>Ver recomendações <ChevronRight/></button></article></section>
  <section className="panel quick-posts"><div className="panel-head"><div><span className="eyebrow">PUBLICAÇÕES</span><h3>Seus conteúdos recentes</h3></div><button onClick={()=>go('/app/criador/publicacoes')}>Ver todos <ChevronRight/></button></div><div className="video-list">{videos.slice(0,2).map(v=><VideoRow key={v.title} v={v}/>)}</div></section>
 </>
}
function Metric({icon:Icon,label,value,delta}:{icon:any;label:string;value:string;delta?:string}){return <article className="metric"><span><Icon/></span><div><small>{label}</small><strong>{value}</strong>{delta&&<em>{delta}</em>}</div></article>}
function VideoRow({v}:{v:any}){return <article className="video-row"><div className="thumb"><img src={v.img}/><i><Play/></i><b>{v.date}</b></div><div className="video-info"><h4>{v.title}</h4><small>Taxa de conclusão: {v.completion}</small><div><span><Eye/>{v.views}</span><span><MessageIcon/>{v.comments}</span><span><Heart/>{v.likes}</span><span><Share2/>{v.shares}</span></div></div><ChevronRight/></article>}
function MessageIcon(){return <span className="message-icon"/>}
function Posts(){return <section className="panel page-panel"><div className="panel-head"><div><span className="eyebrow">CONTEÚDO</span><h3>Desempenho das publicações</h3></div><button className="mini-create" onClick={()=>go('/app/criar/post')}><Plus/> Publicar</button></div><div className="post-summary"><Metric icon={Eye} label="Visualizações" value="47,9 mil" delta="+1.284"/><Metric icon={Heart} label="Curtidas" value="1.438" delta="+87"/><Metric icon={Share2} label="Compartilhamentos" value="584" delta="+29"/></div><div className="video-list">{videos.map(v=><VideoRow key={v.title} v={v}/>)}</div></section>}
function Followers({period}:{period:string}){return <section className="followers-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">AUDIÊNCIA</span><h3>Crescimento de seguidores</h3></div><span className="positive">+{period==='7'?'4':'11'}</span></div><div className="big-number">{period==='7'?'117':'128'} <small>seguidores</small></div><div className="bars">{[35,42,38,57,51,69,82,74,91,88,95,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="chart-labels"><span>Início</span><span>Hoje</span></div></article><article className="panel audience"><div className="panel-head"><div><span className="eyebrow">DISTRIBUIÇÃO</span><h3>Seu público</h3></div></div><div className="donut"><div><b>100%</b><small>Brasil</small></div></div><div className="audience-lines"><span><i/>Brasil <b>98%</b></span><span><i/>Outros <b>2%</b></span></div></article></section>}
function Income(){return <section className="income-grid"><article className="panel income-main"><div className="panel-head"><div><span className="eyebrow">MONETIZAÇÃO</span><h3>Visão geral dos rendimentos</h3></div><button>Últimos 30 dias <ChevronRight/></button></div><div className="income-number">R$ 0,00</div><p>Você ainda não possui rendimentos neste período.</p><div className="income-empty"><Coins/><b>Comece a participar de oportunidades</b><span>Complete tarefas, publique conteúdo elegível e acompanhe suas oportunidades de monetização.</span><button>Ver oportunidades <ArrowLeft/></button></div></article><article className="panel opportunities"><span className="eyebrow">OPORTUNIDADES</span><h3>Formas de ganhar no FLOW</h3>{['Tarefas para criadores','Campanhas com marcas','Ganhos por visualizações','Programa de afiliados'].map((x,i)=><button key={x}><span>{i+1}</span><b>{x}</b><ChevronRight/></button>)}</article></section>}
function CreateModal({close}:{close:()=>void}){return <div className="modal-backdrop" onClick={close}><div className="create-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">CRIAR NO FLOW</span><h2>O que você quer publicar?</h2><p>Escolha um formato para começar sua próxima criação.</p><div className="create-options"><button onClick={()=>go('/app/criar/post')}><ImageIcon/><b>Publicação</b><small>Foto, vídeo ou texto</small></button><button onClick={()=>go('/app/criar/short')}><Play/><b>Short</b><small>Vídeo curto vertical</small></button><button onClick={()=>go('/app/stories')}><Sparkles/><b>Story</b><small>Conteúdo por 24 horas</small></button><button onClick={()=>go('/app/live')}><Video/><b>Live</b><small>Transmissão ao vivo</small></button></div></div></div>}
function ImageIcon(){return <span className="image-icon">▧</span>}
