import { useMemo, useRef, useState } from 'react';
import { Heart, MessageCircle, Send, Bookmark, Search, Home, Compass, Plus, Play, User, Bell, Mail, Settings, MoreHorizontal, LogOut, Image as ImageIcon, Video, X, Check, ChevronLeft, ChevronRight, Users, Hash, Sparkles, Camera, Upload, Music2, Share2 } from 'lucide-react';

type Post={id:number,user:string,name:string,avatar:string,media:string,video?:boolean,caption:string,likes:number,comments:number,liked?:boolean,saved?:boolean};
const seed:Post[]=[
{id:1,user:'flow.creator',name:'Flow Creator',avatar:'https://i.pravatar.cc/100?img=12',media:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1000',caption:'Criando, descobrindo e compartilhando no FLOW. ✨',likes:1842,comments:96},
{id:2,user:'maria.flow',name:'Maria Flow',avatar:'https://i.pravatar.cc/100?img=32',media:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1000',caption:'Ideias que ganham vida. O seu próximo projeto começa aqui.',likes:928,comments:41,liked:true},
{id:3,user:'joao.cria',name:'João Cria',avatar:'https://i.pravatar.cc/100?img=53',media:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1000',caption:'Qual seria o seu FLOW hoje? 🌎',likes:3210,comments:184,saved:true},
{id:4,user:'nina.live',name:'Nina Live',avatar:'https://i.pravatar.cc/100?img=47',media:'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=1000',caption:'Momentos que merecem ser compartilhados.',likes:761,comments:29}];
const people=['Você','Ana','Lucas','Bia','Carlos','Nina','Rafa','Lia'];
const shorts=[1,2,3,4].map((n,i)=>({id:n,user:['travel.flow','music.flow','sport.flow','food.flow'][i],avatar:`https://i.pravatar.cc/100?img=${20+i}`,media:['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=700','https://images.unsplash.com/photo-1519681393784-d120267933ba?w=700','https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=700','https://images.unsplash.com/photo-1547592180-85f173990554?w=700'][i],caption:['Viaje, descubra, viva.','Som que coloca você no FLOW.','Energia em movimento.','Receita rápida para hoje.'][i]}));

export default function FlowWeb(){
 const [tab,setTab]=useState('home'),[feedMode,setFeedMode]=useState('foryou'),[posts,setPosts]=useState<Post[]>(()=>{try{return JSON.parse(localStorage.getItem('flow.posts')||'null')||seed}catch{return seed}}),[auth,setAuth]=useState(localStorage.getItem('flow.auth')==='1'),[showCreate,setShowCreate]=useState(false),[showSearch,setShowSearch]=useState(false),[selectedPost,setSelectedPost]=useState<Post|null>(null),[query,setQuery]=useState('');
 const navigate=(t:string)=>{setTab(t);window.scrollTo({top:0,behavior:'smooth'})};
 const update=(id:number,key:'liked'|'saved')=>setPosts(p=>{const next=p.map(x=>x.id===id?{...x,[key]:!x[key],likes:key==='liked'?x.likes+(x.liked?-1:1):x.likes}:x);localStorage.setItem('flow.posts',JSON.stringify(next));return next});
 const ranked=useMemo(()=>[...posts].sort((a,b)=>(b.likes+b.comments*3)-(a.likes+a.comments*3)),[posts]);
 if(!auth)return <Auth onDone={()=>{localStorage.setItem('flow.auth','1');setAuth(true)}}/>;
 return <div className="flow-shell">
  <header className="topbar"><button className="brand" onClick={()=>navigate('home')}>flow<span>•</span></button><div className="top-search" onClick={()=>setShowSearch(true)}><Search size={18}/><span>Pesquisar no FLOW</span></div><div className="top-actions"><button onClick={()=>navigate('notifications')}><Bell/></button><button onClick={()=>navigate('messages')}><Mail/></button><button className="avatar-btn" onClick={()=>navigate('profile')}><img src="https://i.pravatar.cc/80?img=68"/></button></div></header>
  <div className="layout"><aside className="sidebar"><Nav icon={<Home/>} label="Início" active={tab==='home'} onClick={()=>navigate('home')}/><Nav icon={<Compass/>} label="Explorar" active={tab==='explore'} onClick={()=>navigate('explore')}/><Nav icon={<Play/>} label="Shorts" active={tab==='shorts'} onClick={()=>navigate('shorts')}/><Nav icon={<Plus/>} label="Criar" onClick={()=>setShowCreate(true)}/><Nav icon={<Mail/>} label="Mensagens" active={tab==='messages'} onClick={()=>navigate('messages')}/><Nav icon={<Bell/>} label="Notificações" active={tab==='notifications'} onClick={()=>navigate('notifications')}/><Nav icon={<Users/>} label="Comunidades" active={tab==='communities'} onClick={()=>navigate('communities')}/><Nav icon={<User/>} label="Perfil" active={tab==='profile'} onClick={()=>navigate('profile')}/><div className="nav-spacer"/><Nav icon={<Settings/>} label="Configurações" active={tab==='settings'} onClick={()=>navigate('settings')}/><Nav icon={<LogOut/>} label="Sair" onClick={()=>{localStorage.removeItem('flow.auth');setAuth(false)}}/></aside>
   <main className="main-content">{tab==='home'&&<HomeFeed mode={feedMode} setMode={setFeedMode} posts={ranked} update={update} onComment={setSelectedPost}/>} {tab==='explore'&&<Explore query={query}/>} {tab==='shorts'&&<Shorts/>} {tab==='profile'&&<Profile navigate={navigate}/>} {tab==='messages'&&<Messages/>} {tab==='notifications'&&<Notifications/>} {tab==='communities'&&<Communities/>} {tab==='settings'&&<SettingsView/>}</main>
   <aside className="right-rail"><div className="profile-mini"><img src="https://i.pravatar.cc/100?img=68"/><div><b>@seu.flow</b><span>Seu perfil</span></div><button>Trocar</button></div><div className="rail-title"><b>Sugestões para você</b><button>Ver tudo</button></div>{people.slice(1,6).map((p,i)=><div className="suggest" key={p}><img src={`https://i.pravatar.cc/70?img=${i+3}`}/><div><b>{p.toLowerCase()}.flow</b><span>Sugestão para você</span></div><button>Seguir</button></div>)}<footer>FLOW · Sobre · Ajuda · Privacidade · Termos · © 2026 FLOW</footer></aside>
  </div><nav className="mobile-nav"><Nav icon={<Home/>} active={tab==='home'} onClick={()=>navigate('home')}/><Nav icon={<Search/>} active={tab==='explore'} onClick={()=>navigate('explore')}/><Nav icon={<Plus/>} onClick={()=>setShowCreate(true)}/><Nav icon={<Play/>} active={tab==='shorts'} onClick={()=>navigate('shorts')}/><Nav icon={<User/>} active={tab==='profile'} onClick={()=>navigate('profile')}/></nav>
  {showCreate&&<CreateModal close={()=>setShowCreate(false)}/>} {selectedPost&&<Comments post={selectedPost} close={()=>setSelectedPost(null)}/>} {showSearch&&<SearchModal value={query} setValue={setQuery} close={()=>setShowSearch(false)}/>}</div>}
function Nav({icon,label,active,onClick}:{icon:any,label?:string,active?:boolean,onClick:()=>void}){return <button className={`side-nav ${active?'active':''}`} onClick={onClick}>{icon}{label&&<span>{label}</span>}</button>}
function Auth({onDone}:{onDone:()=>void}){const [mode,setMode]=useState<'login'|'register'>('login');const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [name,setName]=useState('');return <div className="auth-page"><div className="auth-visual"><div className="auth-logo">flow<span>•</span></div><h1>Seu mundo.<br/>Em movimento.</h1><p>Uma rede social para descobrir, criar e conectar.</p></div><div className="auth-card"><div className="auth-mobile-logo">flow<span>•</span></div><h2>{mode==='login'?'Entrar no FLOW':'Criar sua conta'}</h2><p>{mode==='login'?'Continue de onde você parou.':'Comece gratuitamente.'}</p>{mode==='register'&&<input placeholder="Nome completo" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={pass} onChange={e=>setPass(e.target.value)}/><button className="primary-btn" onClick={onDone}>{mode==='login'?'Entrar':'Criar conta'}</button>{mode==='login'&&<button className="text-btn">Esqueci minha senha</button>}<div className="divider"><span>ou</span></div><button className="outline-btn" onClick={onDone}>Continuar com conta de demonstração</button><p className="auth-switch">{mode==='login'?'Não tem uma conta?':'Já tem uma conta?'} <button onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Criar conta':'Entrar'}</button></p><small>Experiência local para desenvolvimento. Nenhuma senha é enviada.</small></div></div>}
function HomeFeed({mode,setMode,posts,update,onComment}:{mode:string,setMode:(x:string)=>void,posts:Post[],update:(id:number,k:'liked'|'saved')=>void,onComment:(p:Post)=>void}){return <div className="feed-column"><div className="feed-switch"><button className={mode==='foryou'?'active':''} onClick={()=>setMode('foryou')}>For You</button><button className={mode==='following'?'active':''} onClick={()=>setMode('following')}>Following</button></div><div className="stories">{people.map((p,i)=><div className="story" key={p}><div className="story-ring"><img src={`https://i.pravatar.cc/100?img=${i+1}`}/>{i===0&&<span>+</span>}</div><small>{p}</small></div>)}</div>{posts.map(p=><PostCard key={p.id} post={p} update={update} onComment={()=>onComment(p)}/>)}</div>}
function PostCard({post,update,onComment}:{post:Post,update:(id:number,k:'liked'|'saved')=>void,onComment:()=>void}){return <article className="post-card"><div className="post-head"><img src={post.avatar}/><div><b>@{post.user}</b><span>{post.name} · agora</span></div><button><MoreHorizontal/></button></div><div className="post-media"><img src={post.media}/>{post.video&&<div className="play-overlay"><Play fill="white"/></div>}</div><div className="post-body"><div className="post-actions"><button className={post.liked?'liked':''} onClick={()=>update(post.id,'liked')}><Heart fill={post.liked?'currentColor':'none'}/></button><button onClick={onComment}><MessageCircle/></button><button><Send/></button><button className={`save ${post.saved?'saved':''}`} onClick={()=>update(post.id,'saved')}><Bookmark fill={post.saved?'currentColor':'none'}/></button></div><b>{post.likes.toLocaleString('pt-BR')} curtidas</b><p><strong>@{post.user}</strong> {post.caption}</p><button className="comments-link" onClick={onComment}>Ver todos os {post.comments} comentários</button><div className="quick-comment"><input placeholder="Adicione um comentário..."/><button>Publicar</button></div></div></article>}
function Explore({query}:{query:string}){const items=seed.concat(seed).filter(x=>!query||x.caption.toLowerCase().includes(query.toLowerCase())||x.user.includes(query));return <section className="page"><div className="page-title"><div><h1>Explorar</h1><p>Descubra novas pessoas, assuntos e tendências.</p></div><div className="explore-search"><Search/><input placeholder="Pesquisar" value={query} readOnly/></div></div><div className="explore-grid">{items.map((p,i)=><div className={`explore-tile ${i%7===0?'wide':''}`} key={i}><img src={p.media}/><div><Heart/> {p.likes.toLocaleString('pt-BR')} · <MessageCircle/> {p.comments}</div></div>)}</div></section>}
function Shorts(){const [index,setIndex]=useState(0),[liked,setLiked]=useState(false);const s=shorts[index];return <section className="shorts-page"><div className="shorts-header"><h1>Shorts</h1><span>For You</span></div><div className="short-player"><img src={s.media}/><div className="short-gradient"/><div className="short-info"><div className="short-user"><img src={s.avatar}/><b>@{s.user}</b><button>Seguir</button></div><p>{s.caption}</p><span><Music2/> Som original · FLOW</span></div><div className="short-actions"><button className={liked?'liked':''} onClick={()=>setLiked(!liked)}><Heart fill={liked?'currentColor':'none'}/><small>1,2 mil</small></button><button><MessageCircle/><small>89</small></button><button><Share2/></button><button><Bookmark/></button></div><button className="short-prev" onClick={()=>{setIndex(Math.max(0,index-1));setLiked(false)}}><ChevronLeft/></button><button className="short-next" onClick={()=>{setIndex(Math.min(shorts.length-1,index+1));setLiked(false)}}><ChevronRight/></button></div></section>}
function Profile({navigate}:{navigate:(x:string)=>void}){const [following,setFollowing]=useState(false);return <section className="page profile-page"><div className="profile-header"><img className="profile-avatar" src="https://i.pravatar.cc/180?img=68"/><div className="profile-info"><h1>Seu Nome <span className="verified"><Check/></span></h1><b>@seu.flow</b><p>Criador no FLOW · compartilhando ideias, momentos e histórias.</p><div className="stats"><span><b>124</b> publicações</span><span><b>18,4 mil</b> seguidores</span><span><b>421</b> seguindo</span></div><div><button className="primary-small" onClick={()=>setFollowing(!following)}>{following?'Seguindo':'Editar perfil'}</button><button className="outline-small" onClick={()=>navigate('settings')}>Configurações</button></div></div></div><div className="profile-tabs"><button>Publicações</button><button>Shorts</button><button>Salvos</button></div><div className="profile-grid">{seed.concat(seed).map((p,i)=><img key={i} src={p.media}/>)}</div></section>}
function Messages(){const [selected,setSelected]=useState(0);const chats=['Ana Flow','Lucas Silva','Bia Criativa','Nina Live'];return <section className="messages-page"><div className="chat-list"><h1>Mensagens</h1><div className="message-search"><Search/> <input placeholder="Pesquisar mensagens"/></div>{chats.map((c,i)=><button className={`chat ${selected===i?'active':''}`} onClick={()=>setSelected(i)} key={c}><img src={`https://i.pravatar.cc/70?img=${10+i}`}/><div><b>{c}</b><span>{i===0?'Oi! Vamos criar algo?':'Você: Tudo certo!'}</span></div><small>{i+1}h</small></button>)}</div><div className="chat-window"><div className="chat-top"><img src="https://i.pravatar.cc/70?img=10"/><b>{chats[selected]}</b></div><div className="chat-empty"><MessageCircle/><h2>Comece a conversa</h2><p>Envie uma mensagem, foto ou vídeo.</p></div><div className="composer"><Plus/><input placeholder="Escreva uma mensagem..."/><Camera/><button><Send/></button></div></div></section>}
function Notifications(){return <section className="page"><h1>Notificações</h1><p className="sub">Veja o que está acontecendo no seu FLOW.</p><div className="notification-list">{['Ana Flow curtiu sua publicação.','Lucas começou a seguir você.','Seu vídeo entrou nos destaques do FLOW.','Bia comentou: “Que incrível!”','Nina mencionou você em um Short.'].map((x,i)=><div className="notification" key={x}><img src={`https://i.pravatar.cc/70?img=${15+i}`}/><p>{x}<span>{i+1}h</span></p><button>Ver</button></div>)}</div></section>}
function Communities(){return <section className="page"><div className="page-title"><div><h1>Comunidades</h1><p>Encontre pessoas que compartilham seus interesses.</p></div><button className="primary-small"><Plus/> Criar comunidade</button></div><div className="community-grid">{['Tecnologia','Música','Games','Fotografia','Viagens','Esportes'].map((x,i)=><div className="community" key={x}><div className="community-cover"/><div className="community-body"><div className="community-icon"><Hash/></div><h2>{x}</h2><p>Converse, publique e descubra conteúdos sobre {x.toLowerCase()}.</p><span>12,4 mil membros</span><button>Entrar</button></div></div>)}</div></section>}
function SettingsView(){return <section className="page settings-page"><h1>Configurações</h1><div className="settings-layout"><div className="settings-menu">{['Conta','Privacidade','Notificações','Segurança','Conteúdo e preferências','Central de ajuda'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="settings-panel"><h2>Conta</h2><label>Nome de usuário<input value="@seu.flow" readOnly/></label><label>E-mail<input value="usuario@flow.local" readOnly/></label><label>Bio<textarea defaultValue="Criador no FLOW · compartilhando ideias, momentos e histórias."/></label><button className="primary-small">Salvar alterações</button><div className="danger-zone"><h3>Zona de segurança</h3><p>Gerencie sessões e dados locais deste navegador.</p><button className="danger">Encerrar todas as sessões</button></div></div></div></section>}
function CreateModal({close}:{close:()=>void}){const [type,setType]=useState<'post'|'short'>('post'),[caption,setCaption]=useState('');const file=useRef<HTMLInputElement>(null);return <div className="modal-backdrop"><div className="modal create-modal"><button className="modal-close" onClick={close}><X/></button><h2>Criar no FLOW</h2><div className="create-tabs"><button className={type==='post'?'active':''} onClick={()=>setType('post')}><ImageIcon/> Publicação</button><button className={type==='short'?'active':''} onClick={()=>setType('short')}><Video/> Short</button></div><div className="upload-box" onClick={()=>file.current?.click()}><Upload/><h3>Selecione sua mídia</h3><p>Fotos e vídeos até 100 MB</p><button className="outline-small">Selecionar arquivo</button><input ref={file} type="file" hidden accept="image/*,video/*"/></div><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Escreva uma legenda..."/><div className="create-options"><button><Sparkles/> Filtros</button><button><Music2/> Música</button><button><Camera/> Marcar pessoas</button></div><button className="primary-btn" onClick={close}>Publicar no FLOW</button></div></div>}
function Comments({post,close}:{post:Post,close:()=>void}){const [text,setText]=useState(''),[list,setList]=useState(['Que conteúdo incrível!','Adorei isso 🔥','O FLOW ficou muito bom!']);return <div className="modal-backdrop"><div className="modal comments-modal"><button className="modal-close" onClick={close}><X/></button><div className="comments-media"><img src={post.media}/></div><div className="comments-panel"><h2>Comentários</h2><div className="comment-list">{list.map((x,i)=><div className="comment-row" key={i}><img src={`https://i.pravatar.cc/50?img=${20+i}`}/><p><b>usuario.flow</b> {x}<span>Curtir · Responder</span></p></div>)}</div><div className="comment-composer"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Adicione um comentário..."/><button onClick={()=>{if(text.trim()){setList([...list,text]);setText('')}}}>Publicar</button></div></div></div></div>}
function SearchModal({value,setValue,close}:{value:string,setValue:(x:string)=>void,close:()=>void}){return <div className="modal-backdrop search-backdrop"><div className="search-modal"><div className="search-modal-head"><h2>Pesquisar</h2><button onClick={close}><X/></button></div><div className="big-search"><Search/><input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="Pessoas, temas e conteúdo"/></div><h3>Pesquisas recentes</h3>{['tecnologia','viagem','música','fotografia'].map(x=><button className="recent" key={x} onClick={()=>setValue(x)}><Search/> {x}</button>)}</div></div>}
