import {useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock3,ExternalLink,Flag,Gift,Heart,Lock,Megaphone,Package,Plus,Search,ShieldCheck,ShoppingBag,Store,Wallet,X} from 'lucide-react';
import {RewardsPage} from './rewards/RewardsPage';
import './platform-modules.css';

type Screen='shop'|'seller'|'orders'|'rewards'|'ads'|'report'|'safety';
const go=(p:string)=>{history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'));window.scrollTo(0,0)};
const products=[{id:'1',name:'Tênis urbano',price:189.9,cat:'Moda',seller:'Flow Store',img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80'},{id:'2',name:'Câmera compacta',price:749,cat:'Eletrônicos',seller:'Studio Shop',img:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=700&q=80'},{id:'3',name:'Mochila urbana',price:219,cat:'Acessórios',seller:'Norte',img:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80'}];
export default function PlatformModules({screen}:{screen:Screen}){if(screen==='rewards')return <RewardsPage/>;if(screen==='shop')return <Shop/>;if(screen==='seller')return <Seller/>;if(screen==='orders')return <Orders/>;if(screen==='ads')return <Ads/>;if(screen==='report')return <Report/>;return <Safety/>}
function Shell({title,children}:{title:string;children:React.ReactNode}){return <div className="module"><header className="module-head"><button onClick={()=>go('/app')}><ArrowLeft/> FLOW</button><h1>{title}</h1><button onClick={()=>go('/app')}><X/></button></header>{children}</div>}
function Shop(){const[query,setQuery]=useState('');const[cart,setCart]=useState<string[]>([]);const filtered=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||p.cat.toLowerCase().includes(query.toLowerCase()));return <Shell title="FLOW Shop"><div className="shop-top"><div><span className="eyebrow">MARKETPLACE</span><h2>Compre de pessoas e lojas.</h2><p>Produtos, ofertas e criadores em uma experiência segura.</p></div><button className="primary" onClick={()=>go('/app/pedidos')}><Package/> Meus pedidos</button></div><div className="shop-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produtos no FLOW Shop"/><button onClick={()=>go('/app/loja')}>Minha loja</button></div><div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><img src={p.img}/><div className="product-body"><small>{p.cat} · {p.seller}</small><h3>{p.name}</h3><strong>R$ {p.price.toFixed(2).replace('.',',')}</strong><button className="primary" onClick={()=>setCart(c=>c.includes(p.id)?c:c.concat(p.id))}>{cart.includes(p.id)?<CheckCircle2/>:<ShoppingBag/>}{cart.includes(p.id)?'Adicionado':'Adicionar'}</button></div></article>)}</div><div className="shop-note"><ShieldCheck/><div><b>Proteção FLOW Shop</b><p>O vendedor é responsável pelo produto e envio. A liberação do repasse segue as condições de proteção da venda.</p></div></div></Shell>}
function Seller(){return <Shell title="Minha loja"><div className="seller-hero"><Store/><div><span className="eyebrow">LOJA</span><h2>Sua vitrine no FLOW</h2><p>Gerencie produtos, pedidos, clientes e repasses.</p></div><button className="primary"><Plus/> Novo produto</button></div><div className="stats"><b><strong>24</strong>Produtos ativos</b><b><strong>R$ 8.420</strong>Vendas</b><b><strong>R$ 6.981</strong>A receber</b><b><strong>0</strong>Alertas</b></div><div className="table"><div><b>Produto</b><b>Status</b><b>Proteção</b><b>Repasse</b></div>{products.map(p=><div key={p.id}><span>{p.name}</span><span className="ok">Publicado</span><span>Protegida</span><span>Elegível após prazo</span></div>)}</div></Shell>}
function Orders(){const[issue,setIssue]=useState(false);return <Shell title="Meus pedidos"><div className="order-card"><div className="order-icon"><Package/></div><div className="order-main"><small>PEDIDO #FLOW-10482</small><h3>Tênis urbano</h3><p>Entrega confirmada · proteção ativa</p><div className="timeline"><span className="done">Pago</span><span className="done">Enviado</span><span className="done">Entregue</span><span>Proteção · 7 dias</span><span>Repasse</span></div></div><strong>R$ 189,90</strong></div><div className="protection"><ShieldCheck/><div><b>Você está protegido</b><p>Em caso de problema, abra uma reclamação dentro do prazo informado no pedido.</p></div><button onClick={()=>setIssue(true)}>Reclamar</button></div>{issue&&<div className="modal"><div><button onClick={()=>setIssue(false)}><X/></button><h2>Qual o problema?</h2>{['Produto não recebido','Produto danificado','Produto diferente do anúncio','Quero devolver'].map(x=><button className="option" key={x} onClick={()=>setIssue(false)}>{x}</button>)}</div></div>}</Shell>}
function Ads(){const[submitted,setSubmitted]=useState(false);return <Shell title="FLOW Ads"><div className="ads-hero"><Megaphone/><div><span className="eyebrow">ANUNCIE</span><h2>Alcance pessoas dentro do FLOW.</h2><p>Anúncios passam por análise e controles de segurança antes da publicação.</p></div></div><div className="ad-form"><label>Nome da empresa<input placeholder="Empresa / marca"/></label><label>CNPJ<input placeholder="00.000.000/0000-00"/></label><label>Destino do anúncio<input placeholder="https://seu-dominio.com.br"/></label><div className="policy"><Lock/><span>Destinos externos exigem verificação manual. Após aprovação, alterações de domínio exigem nova revisão.</span></div><button className="primary" onClick={()=>setSubmitted(true)}>{submitted?'Solicitação enviada':'Enviar para revisão'} <ShieldCheck/></button></div></Shell>}
function Report(){const[done,setDone]=useState(false);const[category,setCategory]=useState('');return <Shell title="Denunciar"><div className="report-box"><Flag/><span className="eyebrow">CENTRAL DE DENÚNCIAS</span><h2>Ajude a manter o FLOW seguro.</h2><p>Informe conteúdo, anúncio, produto ou perfil que viole as regras.</p><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Selecione</option><option>Pirataria / falsificação</option><option>Golpe / fraude</option><option>Pornografia / conteúdo sexual</option><option>Violência</option><option>Produto proibido</option><option>Outro</option></select></label><label>Descrição<textarea placeholder="Conte o que aconteceu..."/></label><label>URL do conteúdo<input placeholder="https://flow..."/></label><button className="primary" onClick={()=>setDone(true)}>{done?'Denúncia registrada':'Enviar denúncia'}</button>{done&&<div className="success"><CheckCircle2/> Denúncia registrada. Protocolo FLOW-2026-001284.</div>}</div></Shell>}
function Safety(){const rules=useMemo(()=>['Pirataria, falsificações e uso não autorizado de propriedade intelectual','Pornografia, nudez sexual explícita e exploração sexual','Produtos de saúde ou emagrecimento sem os requisitos regulatórios aplicáveis','Golpes, phishing, malware e práticas fraudulentas','Armas, drogas ilícitas e outros produtos proibidos','Conteúdo que coloque crianças e adolescentes em risco'],[]);return <Shell title="Segurança e confiança"><div className="safety-grid"><div><span className="eyebrow">TRUST & SAFETY</span><h2>Segurança desde a publicação.</h2><p>Conteúdo, produtos e anúncios passam por políticas, sinais de risco e mecanismos de denúncia.</p><button className="primary" onClick={()=>go('/app/denunciar')}><Flag/> Denunciar</button></div><div className="rule-list">{rules.map(r=><div key={r}><AlertTriangle/><span>{r}</span></div>)}</div></div><div className="safety-cards"><article><ShieldCheck/><b>Verificação</b><p>Contas e empresas seguem os fluxos de identidade definidos pelo FLOW.</p></article><article><Clock3/><b>Revisão</b><p>Casos suspeitos podem ficar retidos para análise antes da distribuição.</p></article><article><Lock/><b>Privacidade</b><p>Dados de identidade não são exibidos publicamente no perfil.</p></article></div></Shell>}
