import { useEffect, useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowLeft, ImagePlus, Save, UserRound } from 'lucide-react';
import { FlowLogo } from '../assets/flowAssets';
import { useAppContext } from '../contexts/AppContext';
import { getDocument } from '../services/firebase/firestore';
import { completeProfile, uploadProfilePhoto } from '../services/firebase/profile';
function go(p:string){history.pushState({},'',p);window.dispatchEvent(new PopStateEvent('popstate'));}
export default function ProfileEditPage(){const{user,loading}=useAppContext();const[name,setName]=useState('');const[phone,setPhone]=useState('');const[city,setCity]=useState('');const[bio,setBio]=useState('');const[cpf,setCpf]=useState('');const[birthDate,setBirthDate]=useState('');const[photo,setPhoto]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 useEffect(()=>{if(!loading&&!user)go('/auth/login');if(user){setName(user.displayName??'');setPhoto(user.photoURL??'');void getDocument<Record<string,unknown>>('users',user.uid).then(p=>{if(!p)return;setName(String(p.name??user.displayName??''));setPhone(String(p.phone??''));setCity(String(p.city??''));setBio(String(p.bio??''));setCpf(String(p.cpf??''));setBirthDate(String(p.birthDate??''));})}},[loading,user]);
 async function photoChange(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{setBusy(true);setError('');setPhoto(await uploadProfilePhoto(f));setMessage('Foto atualizada.')}catch(x){setError(x instanceof Error?x.message:'Falha ao enviar foto.')}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();if(!user)return;try{setBusy(true);setError('');await completeProfile({name,cpf,birthDate,phone,city,bio});setMessage('Perfil atualizado com sucesso.')}catch(x){setError(x instanceof Error?x.message:'Não foi possível salvar.')}finally{setBusy(false)}}
 if(loading||!user)return <main className="flow-complete-page"><div className="flow-complete-card">Carregando…</div></main>;
 return <main className="flow-complete-page"><div className="flow-complete-card"><button type="button" onClick={()=>go('/app/perfil')}><ArrowLeft size={17}/> Voltar</button><FlowLogo className="flow-complete-logo" alt="FLOW"/><h1>Editar meu perfil</h1><p>Personalize sua identidade na FLOW. Suas alterações ficam vinculadas à sua conta.</p><div className="flow-complete-photo"><div className="flow-complete-avatar">{photo?<img src={photo} alt="Sua foto"/>:<UserRound size={42}/>}</div><label className="flow-photo-button"><ImagePlus size={17}/>Alterar foto<input type="file" accept="image/*" onChange={photoChange} disabled={busy}/></label></div><form onSubmit={submit} className="flow-complete-form"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>CPF<input value={cpf} onChange={e=>setCpf(e.target.value)} inputMode="numeric" required/></label><div className="flow-complete-grid"><label>Data de nascimento<input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} required/></label><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel"/></label></div><label>Cidade e estado<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value.slice(0,160))} rows={4}/></label>{error&&<div className="flow-complete-error" role="alert">{error}</div>}{message&&<div className="flow-complete-success" role="status">{message}</div>}<button className="flow-complete-submit" disabled={busy}>{busy?'Salvando…':'Salvar alterações'} <Save size={18}/></button></form></div></main>;
}
