import { useEffect, useMemo, useState } from 'react';
import { FlowIcon, FlowLogo } from '../assets/flowAssets';
import { useAppContext } from '../contexts/AppContext';
import { cancelSchedule, createSchedule, deleteSchedule, duplicateSchedule, listSchedules, publishScheduleNow, updateSchedule, type ScheduleStatus, type ScheduledPost } from '../services/firebase/scheduling';
import './schedule-center.css';

const statusLabels: Record<ScheduleStatus, string> = { DRAFT: 'Rascunho', SCHEDULED: 'Agendada', PUBLISHING: 'Publicando', PUBLISHED: 'Publicada', FAILED: 'Falhou', CANCELLED: 'Cancelada' };
const formatDate = (date: Date) => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(date);
const formatTime = (date: Date) => new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(date);
const inputDate = (date: Date) => { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 10); };
const inputTime = (date: Date) => date.toTimeString().slice(0, 5);

export default function ScheduleCenter() {
  const { user, loading } = useAppContext();
  const [items, setItems] = useState<ScheduledPost[]>([]);
  const [view, setView] = useState<'month' | 'list'>('month');
  const [filter, setFilter] = useState<'ALL' | ScheduleStatus>('ALL');
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selected, setSelected] = useState<ScheduledPost | null>(null);
  const [composerOpen, setComposerOpen] = useState(false);
  const [error, setError] = useState('');

  const reload = async () => { try { setError(''); setItems(await listSchedules()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar os agendamentos.'); } };
  useEffect(() => { if (user) void reload(); }, [user]);
  if (loading || !user) return <div className="flow-schedule-loading">Carregando agendamentos…</div>;

  const filtered = items.filter(item => filter === 'ALL' || item.status === filter);
  const monthDays = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }, [month]);
  const forDay = (day: Date) => filtered.filter(item => item.scheduledAt.toDateString() === day.toDateString());

  const mutate = async (action: () => Promise<void>) => { try { setError(''); await action(); setSelected(null); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível atualizar o agendamento.'); } };
  return <div className="flow-schedule-page">
    <header className="flow-schedule-header"><button className="flow-schedule-logo" onClick={() => go('/app')}><FlowLogo alt="FLOW" /></button><div><span>Conteúdo</span><h1>Agendamentos</h1><p>Organize suas publicações em um só lugar.</p></div><button className="flow-schedule-create" onClick={() => setComposerOpen(true)}><FlowIcon name="plus" size={17} /> Criar publicação</button></header>
    <div className="flow-schedule-layout">
      <aside className="flow-schedule-sidebar"><nav><ScheduleNav icon="home" label="Painel" path="/app" /><ScheduleNav icon="edit" label="Conteúdo" path="/app/agendamento" active /><ScheduleNav icon="bookmark" label="Rascunhos" path="/app/agendamento" /><ScheduleNav icon="check" label="Publicados" path="/app/agendamento" /><ScheduleNav icon="filter" label="Calendário" path="/app/agendamento" /></nav><div className="flow-schedule-sidebar-bottom"><ScheduleNav icon="settings" label="Configurações" path="/app/configuracoes" /><button onClick={() => go('/app')}>Voltar ao FLOW</button></div></aside>
      <main className="flow-schedule-main"><div className="flow-schedule-toolbar"><div className="flow-schedule-profile"><span className="flow-schedule-avatar">{user.displayName?.[0]?.toUpperCase() || 'U'}</span><span><strong>{user.displayName || 'Seu perfil'}</strong><small>{user.email}</small></span></div><div className="flow-schedule-actions"><button onClick={() => setView('list')} className={view === 'list' ? 'active' : ''}>Lista</button><button onClick={() => setView('month')} className={view === 'month' ? 'active' : ''}>Mês</button><select aria-label="Filtrar status" value={filter} onChange={event => setFilter(event.target.value as 'ALL' | ScheduleStatus)}><option value="ALL">Todos os status</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></div>{error && <p className="flow-schedule-error" role="alert">{error}</p>}
        {view === 'month' ? <><div className="flow-calendar-head"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Mês anterior"><FlowIcon name="arrow-left" size={18} /></button><button onClick={() => setMonth(new Date())}>Hoje</button><h2>{new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(month)}</h2><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Próximo mês"><FlowIcon name="arrow-right" size={18} /></button></div><div className="flow-calendar"><div className="flow-calendar-week">{['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map(day => <strong key={day}>{day}</strong>)}</div><div className="flow-calendar-grid">{monthDays.map(day => <div className={`flow-calendar-day ${day.getMonth() !== month.getMonth() ? 'muted' : ''}`} key={day.toISOString()}><span>{day.getDate()}</span>{forDay(day).slice(0, 3).map(item => <button key={item.id} onClick={() => setSelected(item)} className={`flow-calendar-item ${item.status.toLowerCase()}`}><small>{formatTime(item.scheduledAt)}</small>{item.mediaUrl && <img src={item.mediaUrl} alt="" />}<b>{item.text || 'Publicação sem texto'}</b></button>)}{forDay(day).length > 3 && <small className="flow-more">+{forDay(day).length - 3} publicações</small>}</div>)}</div></div></> : <ScheduleList items={filtered} onSelect={setSelected} onDelete={id => void mutate(() => deleteSchedule(id))} />}
      </main>
    </div>
    {selected && <ScheduleDetails item={selected} onClose={() => setSelected(null)} onUpdate={action => void mutate(action)} />}
    {composerOpen && <ScheduleComposer onClose={() => setComposerOpen(false)} onCreated={() => { setComposerOpen(false); void reload(); }} />}
  </div>;
}

function ScheduleNav({ icon, label, path, active }: { icon: Parameters<typeof FlowIcon>[0]['name']; label: string; path: string; active?: boolean }) { return <button className={active ? 'active' : ''} onClick={() => go(path)}><FlowIcon name={icon} size={17} /><span>{label}</span></button>; }
function ScheduleList({ items, onSelect, onDelete }: { items: ScheduledPost[]; onSelect: (item: ScheduledPost) => void; onDelete: (id: string) => void }) { return <section className="flow-schedule-list"><div className="flow-schedule-list-head"><span>Conteúdo</span><span>Perfil</span><span>Data e hora</span><span>Status</span><span>Ações</span></div>{items.length === 0 ? <div className="flow-schedule-empty"><FlowIcon name="filter" size={30} /><h2>Nenhum agendamento encontrado</h2><p>Crie uma publicação para organizar seu calendário.</p></div> : items.map(item => <article key={item.id}><div className="flow-schedule-content">{item.mediaUrl && <img src={item.mediaUrl} alt="" />}<span><strong>{item.text || 'Publicação sem texto'}</strong><small>{item.type}</small></span></div><span className="flow-schedule-profile-cell">{item.profileId}</span><time>{formatDate(item.scheduledAt)}<small>{formatTime(item.scheduledAt)}</small></time><span className={`flow-schedule-status ${item.status.toLowerCase()}`}>{statusLabels[item.status]}</span><div className="flow-schedule-row-actions"><button onClick={() => onSelect(item)} aria-label="Visualizar"><FlowIcon name="eye" size={16} /></button><button onClick={() => onDelete(item.id)} aria-label="Excluir"><FlowIcon name="trash" size={16} /></button></div></article>)}</section>; }
function ScheduleDetails({ item, onClose, onUpdate }: { item: ScheduledPost; onClose: () => void; onUpdate: (action: () => Promise<void>) => void }) { return <div className="flow-schedule-overlay"><button className="flow-schedule-backdrop" onClick={onClose} aria-label="Fechar detalhes" /><section className="flow-schedule-details"><header><strong>Detalhes da publicação</strong><button onClick={onClose} aria-label="Fechar"><FlowIcon name="close" size={18} /></button></header>{item.mediaUrl && <img className="flow-schedule-detail-media" src={item.mediaUrl} alt="" />}<p>{item.text || 'Publicação sem texto'}</p><div className="flow-schedule-detail-meta"><span>{formatDate(item.scheduledAt)}</span><span>{formatTime(item.scheduledAt)} · {item.timezone}</span><b className={item.status.toLowerCase()}>{statusLabels[item.status]}</b></div><footer>{item.status === 'SCHEDULED' && <button onClick={() => onUpdate(() => publishScheduleNow(item.id))}>Publicar agora</button>}{item.status === 'SCHEDULED' && <button onClick={() => onUpdate(() => cancelSchedule(item.id))}>Cancelar</button>}<button onClick={() => onUpdate(async () => { await duplicateSchedule(item); })}>Duplicar</button><button className="danger" onClick={() => { if (window.confirm('Excluir esta publicação?')) onUpdate(() => deleteSchedule(item.id)); }}>Excluir</button></footer></section></div>; }
function ScheduleComposer({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [text, setText] = useState(''); const [date, setDate] = useState(inputDate(new Date(Date.now() + 86_400_000))); const [time, setTime] = useState('09:00'); const [status, setStatus] = useState<'DRAFT' | 'SCHEDULED'>('SCHEDULED'); const [error, setError] = useState(''); const submit = async () => { try { const scheduledAt = new Date(`${date}T${time}:00`); if (scheduledAt <= new Date()) throw new Error('Escolha uma data e horário futuros.'); await createSchedule({ profileId: 'self', text, type: 'text', scheduledAt, timezone: 'America/Sao_Paulo', status }); onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível agendar.'); } }; return <div className="flow-schedule-overlay"><button className="flow-schedule-backdrop" onClick={onClose} aria-label="Fechar criação" /><section className="flow-schedule-composer"><header><h2>Criar publicação</h2><button onClick={onClose} aria-label="Fechar"><FlowIcon name="close" size={18} /></button></header><textarea value={text} onChange={event => setText(event.target.value)} placeholder="Escreva o conteúdo da publicação" /><div className="flow-schedule-fields"><label>Data<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label>Hora<input type="time" value={time} onChange={event => setTime(event.target.value)} /></label><label>Fuso<select value="America/Sao_Paulo" disabled><option>America/Sao_Paulo</option></select></label></div>{error && <p className="flow-schedule-error" role="alert">{error}</p>}<footer><button onClick={() => { setStatus('DRAFT'); void submit(); }}>Salvar rascunho</button><button className="primary" onClick={() => { setStatus('SCHEDULED'); void submit(); }}>Agendar publicação</button></footer></section></div>; }
function go(path: string) { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({ top: 0, behavior: 'auto' }); }
