import React from 'react';
import { AlertTriangle, BadgeCheck, BarChart3, Bell, ChevronRight, Flag, Megaphone, Package, Plus, Search, ShoppingBag, Store, Wallet } from 'lucide-react';
import './commerce.css';

const reports=[['FLW-2026-000184','Golpe ou fraude','Post','Em análise','Alta'],['FLW-2026-000183','Spam','Comentário','Recebida','Normal'],['FLW-2026-000182','Segurança de crianças e adolescentes','Vídeo','Em análise','Crítica']];
const products=[['/assets/flow-phone-1.svg','Flow Phone Pro','R$ 1.899,90'],['/assets/flow-phone-2.svg','Flow Phone Lite','R$ 999,90'],['/assets/flow-phone-3.svg','Flow Phone Max','R$ 2.499,90'],['/assets/flow-phone-1.svg','Flow Creator Kit','R$ 349,90']];

export function FlowCommerceHome(){return <div className="commerce-page"><div className="commerce-container"><section className="commerce-hero"><div className="commerce-icon"><ShoppingBag size={21}/></div><h1>FLOW Shop</h1><p>Descubra lojas, produtos e ofertas dentro da experiência social do FLOW.</p><a className="commerce-button" href="/shop/explorar">Explorar produtos <ChevronRight size={16}/></a></section><div className="shop-products">{products.map(([img,name,price],i)=><article className="product-card" key={i}><img src={img} alt=""/><div className="product-card-body"><b>{name}</b><span>{price}</span><button className="commerce-button" style={{marginTop:10}}>Ver produto</button></div></article>)}</div></div></div>}

export function FlowReportPage(){return <div className="commerce-page"><div className="commerce-container"><form className="report-form" onSubmit={e=>{e.preventDefault();alert('Denúncia recebida. Seu protocolo será exibido após o envio.')}}><div className="commerce-icon"><Flag size={20}/></div><h1>Central de denúncias</h1><p>Informe uma irregularidade encontrada no FLOW. Forneça informações objetivas para facilitar a análise.</p><label>O que você deseja denunciar?</label><div className="report-options">{['Conteúdo ilegal','Violência','Segurança de crianças e adolescentes','Assédio','Ódio ou discriminação','Golpe ou fraude','Spam','Direitos autorais','Privacidade','Outro'].map(x=><button type="button" className="report-option" key={x}>{x}</button>)}</div><label>Descrição</label><textarea placeholder="Explique o problema..." style={{width:'100%',minHeight:110,margin:'8px 0 16px',padding:12,border:'1px solid #e6eaf1',borderRadius:10}}/><button className="commerce-button" type="submit">Enviar denúncia</button></form></div></div>}

export function FlowAdsAdmin(){return <div className="commerce-page"><div className="commerce-container"><section className="commerce-hero"><div className="commerce-icon"><Megaphone size={21}/></div><h1>Publicidade</h1><p>Gerencie o inventário de anúncios nativos do FLOW e a integração futura com provedores de publicidade.</p><a className="commerce-button" href="/admin/anuncios">Abrir central de anúncios</a></section><div className="commerce-grid">{[['Campanhas',Megaphone,'12'],['Impressões',BarChart3,'1,28M'],['Cliques',Search,'48,2K'],['Receita',Wallet,'R$ 18.420']].map(([t,I,v])=><div className="commerce-card" key={String(t)}><div className="commerce-icon"><I size={19}/></div><h3>{t}</h3><b>{v}</b><p>Dados demonstrativos preparados para integração com APIs.</p></div>)}</div></div></div>}

export function FlowReportsAdmin(){return <div className="commerce-page"><div className="commerce-container"><section className="commerce-hero"><div className="commerce-icon"><AlertTriangle size={21}/></div><h1>Denúncias</h1><p>Fila de moderação e segurança da plataforma.</p></section><div className="commerce-grid">{reports.map(r=><article className="commerce-card" key={r[0]}><b>{r[0]}</b><h3>{r[1]}</h3><p>{r[2]} · {r[3]} · prioridade {r[4]}</p><button className="commerce-button">Analisar</button></article>)}</div></div></div>}

export function FlowSellerPage(){return <div className="commerce-page"><div className="commerce-container"><section className="commerce-hero"><div className="commerce-icon"><Store size={21}/></div><h1>Minha loja</h1><p>Publique produtos, acompanhe pedidos e construa sua presença comercial dentro do FLOW.</p><a className="commerce-button" href="/shop/vendedor/produtos"><Plus size={16}/> Adicionar produto</a></section><div className="commerce-grid">{[['Produtos',Package,'24'],['Pedidos',ShoppingBag,'86'],['Seguidores',Bell,'3.420'],['Avaliação',BadgeCheck,'4,9']].map(([t,I,v])=><div className="commerce-card" key={String(t)}><div className="commerce-icon"><I size={19}/></div><h3>{t}</h3><b>{v}</b><p>Visão geral da sua operação no FLOW Shop.</p></div>)}</div></div></div>}
