import React,{useMemo,useState} from 'react';
import {AlertCircle,CheckCircle2,Clock3,PackageCheck,RefreshCcw,Truck,WalletCards} from 'lucide-react';
import {calculateCaseDeadline,calculateReleaseDate,BUYER_CONFIRMATION_WINDOW_DAYS,FUNDS_RELEASE_AFTER_CONFIRMATION_DAYS} from './FlowShopPolicy';

const deliveredAt='2026-09-02T12:00:00.000Z';
export function ShopOrderCenter(){const [confirmed,setConfirmed]=useState(false);const [caseOpen,setCaseOpen]=useState(false);const release=useMemo(()=>confirmed?calculateReleaseDate(new Date().toISOString()):null,[confirmed]);return <main style={{maxWidth:900,margin:'32px auto',padding:16,fontFamily:'Inter,system-ui'}}><h1>FLOW Shop · Pedido #FLW-10482</h1><p>Proteção da compra e acompanhamento do pedido.</p><section style={{display:'grid',gap:12,gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))'}}><Card icon={<Truck/>} title="Envio" text="Responsabilidade do vendedor"/><Card icon={<PackageCheck/>} title="Entrega" text="Aguardando confirmação"/><Card icon={<Clock3/>} title="Proteção" text={`Reclamação, troca ou devolução em até ${BUYER_CONFIRMATION_WINDOW_DAYS} dias`}/><Card icon={<WalletCards/>} title="Pagamento ao vendedor" text={confirmed?`Liberação prevista após ${FUNDS_RELEASE_AFTER_CONFIRMATION_DAYS} dias`:'Retido até confirmação do comprador'}/></section><div style={{marginTop:24,padding:20,border:'1px solid #e5e7eb',borderRadius:16}}><h2>Recebi o produto?</h2><p>Confirme somente depois de conferir o produto e verificar se está em boas condições.</p><button onClick={()=>setConfirmed(true)} disabled={confirmed} style={btn}>{confirmed?'✓ Recebimento confirmado':'Confirmar recebimento'}</button>{confirmed&&<p style={{color:'#166534'}}>Recebimento confirmado. Liberação prevista para {new Date(release!).toLocaleDateString('pt-BR')}.</p>}</div><div style={{marginTop:16,padding:20,border:'1px solid #e5e7eb',borderRadius:16}}><h2>Problema com o pedido?</h2><p>Você pode abrir uma reclamação, troca, devolução ou solicitação de reembolso dentro do prazo de proteção.</p><button onClick={()=>setCaseOpen(true)} style={{...btn,background:'#fff',color:'#111827',border:'1px solid #d1d5db'}}><AlertCircle size={16}/> Abrir solicitação</button>{caseOpen&&<div style={{marginTop:15}}><select style={input} defaultValue="complaint"><option value="complaint">Reclamação</option><option value="exchange">Troca</option><option value="return">Devolução</option><option value="refund">Reembolso</option></select><textarea placeholder="Descreva o problema e anexe evidências quando a API estiver conectada." style={{...input,minHeight:100,marginTop:10}}/><button style={{...btn,marginTop:10}} onClick={()=>alert(`Solicitação registrada. Prazo de referência: ${new Date(calculateCaseDeadline(deliveredAt)).toLocaleDateString('pt-BR')}.`)}>Enviar solicitação</button></div>}</div></main>}
function Card({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div style={{padding:18,border:'1px solid #e5e7eb',borderRadius:16}}><div>{icon}</div><strong>{title}</strong><p>{text}</p></div>}
const btn:React.CSSProperties={display:'inline-flex',alignItems:'center',gap:8,padding:'11px 15px',border:0,borderRadius:10,background:'#2563eb',color:'#fff',fontWeight:800,cursor:'pointer'};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:12,border:'1px solid #d1d5db',borderRadius:10};
